### ISSUE TITLE
Subdirectory installation should be reflected in /graphql endpoint url

### ISSUE THREAD

**Issue by luciandinu** [nocio/headstart#1]
I've tested this with your templates...
The idea is that is not clear on how to use it.
Pointing to /graphql url result in an error
file_get_contents(/....../october/composer.json): failed to open stream: No such file or directory

**Comment by frthjf** [comment]
Hi @luciandinu,
Thanks for checking out my plugin. What query are you sending to the /graphql endpoint? In the 'Test' section, can you send the query
```
{
headstart
}
```
? It should return 1 or True.

**Comment by luciandinu** [comment]
Helllo,
`
{
headstart
}
`
It returns: TypeError: Failed to fetch

**Comment by frthjf** [comment]
What October and PHP version are you using?

**Comment by luciandinu** [comment]
I have PHP 7.0 + October build 458.
Ok. I think I know the problem.
I have october in a subfolder like : https://domainame.com/october/ and the plugin tries to access https://domainname.com/graphql .. but this url doesn't exists

**Comment by frthjf** [comment]
I see, that's a bug then; it should use the installation url. I'll fix this in the next version, thanks for reporting. However, the next version of Headstart will require PHP 7.3 or higher as it comes with the latest Lighthouse GraphQL backend. I'll release an update this weekend, watch this space.

**Comment by frthjf** [comment]
This has now been fixed. Please upgrade to the latest Headstart version 1.2.1 and let me know if you encounter any other issues. Thanks.
