### ISSUE TITLE
Missing scalar Mixed on @whereConstraints

### ISSUE THREAD

**Issue by dev-dx** [nocio/headstart#12]
Hi,

I would like to use directive @whereConstraints and scalar Mixed as mentioned on the documentation of lighthouse.
But it got error missing Mixed scalar.

how to configure it on the plugin ?

**Comment by frthjf** [comment]
Hi @dev-dx,

I've never tried that myself but it should work. Did you follow the [setup instructions](https://lighthouse-php.com/4.3/api-reference/directives.html#whereconstraints) in the Lighthouse documentation? In particular, did you add the Mixed scalar `scalar Mixed @scalar(class: "MLL\\GraphQLScalars\\Mixed")` to your schema?
