### ISSUE TITLE
About Filesystem error

### ISSUE THREAD

**Issue by cfuhr** [nocio/headstart#3]
Hi, I have purchased the Headstart license but an error appears.
I am using Laragon for development, where I installed my October CMS project.
The error is with Filesystem
~ / vendor / laravel / framework / src / Illuminate / Filesystem / Filesystem.php

mkdir(): No such file or directory

This error is returned when I want to access the url

http://graphql.localhost:8000/backend/nocio/headstart/schema

I appreciate your help.

Best regards.

--
Claudio

**Comment by frthjf** [comment]
Hi Claudio,

I'm sorry you've been experiencing this issue with Headstart. I've reproduced the bug and released a fix. Please update to the latest version. 

Let me know if you encounter any further issues.

Thanks.

**Comment by cfuhr** [comment]
Thanks Jof.
I already updated to the latest version of Headstart and it doesn't give an error.
Best regards.

--
Claudio

**Comment by frthjf** [comment]
Great, glad it worked.
