### ISSUE TITLE
How to make my api endpoint secure with a token?

### ISSUE THREAD

**Issue by MichaelBrauner** [nocio/headstart#7]
I want to build a gatsby site with octobercms and headstart. 
But when I do mutations, I have to secure the endpoint in some way?

How is the approach to this?

**Comment by frthjf** [comment]
Hi @Slowwie, 
You can install Headstart's [JWTAuth](https://github.com/nocio/headstart/tree/master/templates/rluders_jwtauth) template that provides the Schema for [this OctoberCMS JWT plugin](https://octobercms.com/plugin/rluders-jwtauth) (make sure to install it first). This handles cookie based JWT authentication and provides an authentication middleware.

You can then [protect any of your endpoints (Mutation or Query)](https://github.com/nocio/headstart/blob/master/templates/rluders_jwtauth/schema.htm#L157) using that middleware, for example:
```
extend type Mutation @middleware(checks: ["auth:api"]) {
    test: Int!
}
```
You are of course free to use other middleware / authentication providers.

Hope that helps.

**Comment by MichaelBrauner** [comment]
Ok, that sounds great. I will give it a try.
