### ISSUE TITLE
Installation problems. 

### ISSUE THREAD

**Issue by MichaelBrauner** [nocio/headstart#8]
I just set up an october project (created a project online and bought the headstart plugin - connected it to my new project). 

When I want to install the project - I get an error. Database can not be accessed. And this error comes fom the nocio/headstart plugin. 

I tried the installation without the plugin and it works fine. 

When I search now for ”headstart" in the plugin shop of my new october installation - it does not find headstart... . 

What can this be?

**Comment by frthjf** [comment]
Hi, sorry for the issues. Are you sure you've set up a database for your October installation correctly? October [generally does not require a database](https://octobercms.com/support/article/ob-13), so installations may work without issues. Headstart, however, requires a database. 

Could you provide the full stack-trace (or screenshot of the error page) for the `Database cannot be accessed` error so I can see which file it originates from?

**Comment by MichaelBrauner** [comment]
Hey! I install october via the wizard intallation: [https://octobercms.com/docs/setup/installation#wizard-installation](wizard-installation)

All works fine until it wants to setup the headstart plugin: 

SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) (SQL: select * from `system_settings` where `item` = nocio_headstart_settings limit 1)

But the sql connection is right. Without headstart plugin in works just fine. And  password no is not right. I use a password...

**Comment by frthjf** [comment]
This looks like a general database connection issue. It happens when you navigate on the settings page right? Can you edit your `config/database.php` or `.env` settings to change the `localhost` to `127.0.0.1` (or in the installation wizard change it under `Advanced settings`). On some servers, the loop address resolution is a bit strange.

**Comment by MichaelBrauner** [comment]
No - I do not browse anywhere. Because I dont come to the admin area. The installation of the whole system fails on "Building configuration files". I inserted everwhere 127.0.0.1 instead of localhost - but the problem stays.

**Comment by frthjf** [comment]
If you can't access the admin area, how did you install Headstart?

**Comment by MichaelBrauner** [comment]
I connected it via the october-website. I tried to install headstart from a fresh october installation. But then I can not find headstart. Maybe headstart is not compatible with the newest october?

**Comment by frthjf** [comment]
I see. Could you install October and the User plugin first and see whether that works without issues and then use the settings to connect the project with the Headstart plugin. 

Also, what October build are you using? It might be that you are on a newer version with a newer Laravel. I'll try and see if there were any breaking changes in the latest version. Thanks!

**Comment by MichaelBrauner** [comment]
That worked - thank u!

**Comment by frthjf** [comment]
Great! Thanks for the feedback.
